### ISSUE TITLE
Not compatible Enzyme adapter

### ISSUE THREAD

**Issue by ThisSilenceIsMine** [SelfDevTV/Not-Todo#1]
# enzyme-adapter-react-16 is not compatible with used React version (v17)

Please, consider switching either to 
[Unofficial adapter for React 17](https://www.npmjs.com/package/@wojtekmaj/enzyme-adapter-react-17)

or

[React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)

**Comment by SelfDevTV** [comment]
Thx will do that later today. Nice catch!

**Comment by ThisSilenceIsMine** [comment]
Closed with PR #4
