### ISSUE TITLE
Missing React Query, but got SWR

### ISSUE THREAD

**Issue by ThisSilenceIsMine** [SelfDevTV/Not-Todo#2]
During stack-related discussion React-Query was decided as a go-to solution for querying and syncing data in currenct project. Same settled in Evernote:

> Stack:
> 
> - Next.js
> - Tailwind.css
> - Next-Auth
> - React-Query
> - Hosted on Netlify

Despite that, [package.json](https://github.com/SelfDevTV/Not-Todo/blob/main/package.json) contains SWR dependency, but not React-Query.

Please, consider fixing dependencies or manually close this issue, if everything set correcly and I'm just missed something.

**Comment by SelfDevTV** [comment]
Good point! This came with the mongoose template. I will fix this later today.

**Comment by ThisSilenceIsMine** [comment]
Closed by PR #4
